### Topic: Restaurant Reviews
### Task: Sentiment Classification

##### Student Name: Noora Hussain

1. Task A — Sentiment Classification
- Problem: Classify restaurant reviews by sentiment into three categorical classes.

- Target Audience / User: Restaurant owners and managers looking to monitor customer satisfaction.

- Input: Raw customer review text (in Arabic and English).

- Output: Predicted sentiment label — Positive, Neutral, or Negative.

- Evaluation & Success Metrics: Compare predicted labels against the manually created true labels (true_label) using Accuracy, Precision, Recall, F1-Score, and a Confusion Matrix.

2. Task B — Zero-Shot Topic Classification
- Problem: Automatically identify the primary topic or aspect discussed within a customer review without requiring task-specific training data.

- Target Audience / User: Restaurant operations teams seeking granular feedback on specific business pillars.

- Input: Restaurant review text.

- Output: Categorized topic label selected from predefined operational domains: Food Quality, Service, Price, Cleanliness, Atmosphere, Location, or Waiting Time.

- Evaluation & Success Metrics: Compare zero-shot model predictions against manually assigned ground-truth topic labels.

Task A Dataset :

- Size: 51 annotated restaurant reviews (reflecting a balanced distribution across sentiment classes).

Class Distribution:

- Positive: 23 reviews

- Negative: 16 reviews

- Neutral: 12 reviews

- Language Coverage: Bilingual dataset featuring reviews in both Arabic (33 reviews) and English (18 reviews).

Task B Dataset :

- Size: 35 manually labeled evaluation reviews.

- Target Aspects: Food Quality, Service, Price, Cleanliness, Atmosphere, Location, and Waiting Time.

In [1]:
import pandas as pd

In [2]:
T1_df = pd.read_excel("bahrain_reviews_task_a.xlsx")
T1_df.head()

,id,review_text,true_label,restaurant_name,language
0,1,الشاورما الدجاج واللحم كلها حلوة ولذيذة. والكم...,positive,مطعم الشعلة,Arabic
1,2,الشعلة نار على علم .. سمعته تسبق اسمه😄 احد افض...,positive,مطعم الشعلة,Arabic
2,3,Today I visited for the first time. Half Grill...,negative,مطعم الشعلة,English
3,4,Al shola famous for the Turkish grill have the...,neutral,مطعم الشعلة,English
4,5,Cut the story short: to know the real taste! I...,positive,HAZE Restaurant,English

In [3]:
T1_df.shape

(51, 5)

In [4]:
T1_df["true_label"].value_counts()

true_label
positive    23
negative    16
neutral     12
Name: count, dtype: int64

In [5]:
T2_df = pd.read_excel("bahrain_reviews_task_b.xlsx")
T2_df.head()

,id,review_text,restaurant_name,topic_label
0,1,الشاورما الدجاج واللحم كلها حلوة ولذيذة. والكم...,مطعم الشعلة,Location
1,2,الشعلة نار على علم .. سمعته تسبق اسمه😄 احد افض...,مطعم الشعلة,Food Quality
2,3,Today I visited for the first time. Half Grill...,مطعم الشعلة,Food Quality
3,4,Al shola famous for the Turkish grill have the...,مطعم الشعلة,Location
4,5,Cut the story short: to know the real taste! B...,HAZE Restaurant,Price

In [6]:
T2_df["topic_label"].value_counts()

topic_label
Location        8
Food Quality    8
Service         7
Atmosphere      7
Cleanliness     3
Price           2
Name: count, dtype: int64

In [7]:
#!pip install --upgrade torch transformers

In [8]:
#!pip uninstall -y torch torchvision
#!pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu
#!pip install transformers

In [9]:
!pip install --upgrade --force-reinstall torch torchaudio

Collecting torch
  Using cached torch-2.13.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (38 kB)
Collecting torchaudio
  Using cached torchaudio-2.11.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (6.9 kB)
Collecting filelock (from torch)
  Using cached filelock-3.32.3-py3-none-any.whl.metadata (2.0 kB)
Collecting typing-extensions>=4.10.0 (from torch)
  Using cached typing_extensions-4.16.0-py3-none-any.whl.metadata (3.3 kB)
Collecting setuptools>=77.0.3 (from torch)
  Using cached setuptools-84.0.0-py3-none-any.whl.metadata (6.6 kB)
Collecting sympy>=1.13.3 (from torch)
  Using cached sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Collecting networkx>=2.5.1 (from torch)
  Using cached networkx-3.6.1-py3-none-any.whl.metadata (6.8 kB)
Collecting jinja2 (from torch)
  Using cached jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Collecting fsspec>=0.8.5 (from torch)
  Using cached fsspec-2026.7.0-py3-none-any.whl.metadata (10 kB)
Collecting cuda-toolkit==13.0.3 (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch)
  Using cached cuda_toolkit-13.0.3.0-py2.py3-none-any.whl.metadata (17 kB)
Collecting cuda-bindings<14,>=13.0.3 (from torch)
  Using cached cuda_bindings-13.3.1-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (2.5 kB)
Collecting nvidia-cudnn-cu13==9.20.0.48 (from torch)
  Using cached nvidia_cudnn_cu13-9.20.0.48-py3-none-manylinux_2_27_x86_64.whl.metadata (1.9 kB)
Collecting nvidia-cusparselt-cu13==0.8.1 (from torch)
  Using cached nvidia_cusparselt_cu13-0.8.1-py3-none-manylinux2014_x86_64.whl.metadata (12 kB)
Collecting nvidia-nccl-cu13==2.29.7 (from torch)
  Using cached nvidia_nccl_cu13-2.29.7-py3-none-manylinux_2_18_x86_64.whl.metadata (2.1 kB)
Collecting nvidia-nvshmem-cu13==3.4.5 (from torch)
  Using cached nvidia_nvshmem_cu13-3.4.5-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.1 kB)
Collecting triton==3.7.1 (from torch)
  Using cached triton-3.7.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cublas==13.1.1.3.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch)
  Using cached nvidia_cublas-13.1.1.3-py3-none-manylinux_2_27_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cuda-nvrtc==13.0.88.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch)
  Using cached nvidia_cuda_nvrtc-13.0.88-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-runtime==13.0.96.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch)
  Using cached nvidia_cuda_runtime-13.0.96-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cufft==12.0.0.61.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch)
  Using cached nvidia_cufft-12.0.0.61-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvjitlink<14,>=13.0.88 (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch)
  Using cached nvidia_nvjitlink-13.3.33-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cufile==1.15.1.6.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch)
  Using cached nvidia_cufile-1.15.1.6-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-cupti==13.0.85.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch)
  Using cached nvidia_cuda_cupti-13.0.85-py3-none-manylinux_2_25_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-curand==10.4.0.35.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch)
  Using cached nvidia_curand-10.4.0.35-py3-none-manylinux_2_27_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cusolver==12.0.4.66.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch)
  Using cached nvidia_cusolver-12.0.4.66-py3-none-manylinux_2_27_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cusparse==12.6.3.3.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch)
  Using cached nvidia_cusparse-12.6.3.3-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvtx==13.0.85.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch)
  Using cached nvidia_nvtx-13.0.85-py3-none-manylinux1_x86_64.manylinux_2_5_x86_64.whl.metadata (1.8 kB)
Collecting cuda-pathfinder>=1.4.2 (from cuda-bindings<14,>=13.0.3->torch)
  Using cached cuda_pathfinder-1.6.1-py3-none-any.whl.metadata (1.9 kB)
Collecting mpmath<1.4,>=1.1.0 (from sympy>=1.13.3->torch)
  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Collecting MarkupSafe>=2.0 (from jinja2->torch)
  Using cached markupsafe-3.0.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (2.7 kB)
Using cached torch-2.13.0-cp312-cp312-manylinux_2_28_x86_64.whl (526.6 MB)
Using cached cuda_toolkit-13.0.3.0-py2.py3-none-any.whl (2.5 kB)
Using cached nvidia_cudnn_cu13-9.20.0.48-py3-none-manylinux_2_27_x86_64.whl (366.2 MB)
Using cached nvidia_cusparselt_cu13-0.8.1-py3-none-manylinux2014_x86_64.whl (170.1 MB)
Using cached nvidia_nccl_cu13-2.29.7-py3-none-manylinux_2_18_x86_64.whl (206.0 MB)
Using cached nvidia_nvshmem_cu13-3.4.5-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (60.4 MB)
Using cached triton-3.7.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (197.7 MB)
Using cached nvidia_cublas-13.1.1.3-py3-none-manylinux_2_27_x86_64.whl (423.1 MB)
Using cached nvidia_cuda_cupti-13.0.85-py3-none-manylinux_2_25_x86_64.whl (10.7 MB)
Using cached nvidia_cuda_nvrtc-13.0.88-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl (90.2 MB)
Using cached nvidia_cuda_runtime-13.0.96-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (2.2 MB)
Using cached nvidia_cufft-12.0.0.61-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (214.1 MB)
Using cached nvidia_cufile-1.15.1.6-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (1.2 MB)
Using cached nvidia_curand-10.4.0.35-py3-none-manylinux_2_27_x86_64.whl (59.5 MB)
Using cached nvidia_cusolver-12.0.4.66-py3-none-manylinux_2_27_x86_64.whl (200.9 MB)
Using cached nvidia_cusparse-12.6.3.3-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (145.9 MB)
Using cached nvidia_nvtx-13.0.85-py3-none-manylinux1_x86_64.manylinux_2_5_x86_64.whl (148 kB)
Using cached torchaudio-2.11.0-cp312-cp312-manylinux_2_28_x86_64.whl (1.8 MB)
Using cached cuda_bindings-13.3.1-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (6.7 MB)
Using cached fsspec-2026.7.0-py3-none-any.whl (206 kB)
Using cached networkx-3.6.1-py3-none-any.whl (2.1 MB)
Using cached setuptools-84.0.0-py3-none-any.whl (818 kB)
Using cached sympy-1.14.0-py3-none-any.whl (6.3 MB)
Using cached typing_extensions-4.16.0-py3-none-any.whl (45 kB)
Using cached filelock-3.32.3-py3-none-any.whl (98 kB)
Using cached jinja2-3.1.6-py3-none-any.whl (134 kB)
Using cached cuda_pathfinder-1.6.1-py3-none-any.whl (60 kB)
Using cached markupsafe-3.0.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (22 kB)
Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
Using cached nvidia_nvjitlink-13.3.33-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl (40.7 MB)
Installing collected packages: torchaudio, nvidia-cusparselt-cu13, mpmath, cuda-toolkit, typing-extensions, triton, sympy, setuptools, nvidia-nvtx, nvidia-nvshmem-cu13, nvidia-nvjitlink, nvidia-nccl-cu13, nvidia-curand, nvidia-cufile, nvidia-cuda-runtime, nvidia-cuda-nvrtc, nvidia-cuda-cupti, networkx, MarkupSafe, fsspec, filelock, cuda-pathfinder, nvidia-cusparse, nvidia-cufft, nvidia-cublas, jinja2, cuda-bindings, nvidia-cusolver, nvidia-cudnn-cu13, torch
  Attempting uninstall: torchaudio
    Found existing installation: torchaudio 2.11.0
    Uninstalling torchaudio-2.11.0:
      Successfully uninstalled torchaudio-2.11.0
  Attempting uninstall: nvidia-cusparselt-cu13
    Found existing installation: nvidia-cusparselt-cu13 0.8.1
    Uninstalling nvidia-cusparselt-cu13-0.8.1:
      Successfully uninstalled nvidia-cusparselt-cu13-0.8.1
  Attempting uninstall: mpmath
    Found existing installation: mpmath 1.3.0
    Uninstalling mpmath-1.3.0:
      Successfully uninstalled mpmath-1.3.0
  Attempting uninstall: cuda-toolkit
    Found existing installation: cuda-toolkit 13.0.3.0
    Uninstalling cuda-toolkit-13.0.3.0:
      Successfully uninstalled cuda-toolkit-13.0.3.0
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.16.0
    Uninstalling typing_extensions-4.16.0:
      Successfully uninstalled typing_extensions-4.16.0
  Attempting uninstall: triton
    Found existing installation: triton 3.7.1
    Uninstalling triton-3.7.1:
      Successfully uninstalled triton-3.7.1
  Attempting uninstall: sympy
    Found existing installation: sympy 1.14.0
    Uninstalling sympy-1.14.0:
      Successfully uninstalled sympy-1.14.0
  Attempting uninstall: setuptools
    Found existing installation: setuptools 84.0.0
    Uninstalling setuptools-84.0.0:
      Successfully uninstalled setuptools-84.0.0
  Attempting uninstall: nvidia-nvtx
    Found existing installation: nvidia-nvtx 13.0.85
    Uninstalling nvidia-nvtx-13.0.85:
      Successfully uninstalled nvidia-nvtx-13.0.85
  Attempting uninstall: nvidia-nvshmem-cu13
    Found existing installation: nvidia-nvshmem-cu13 3.4.5
    Uninstalling nvidia-nvshmem-cu13-3.4.5:
      Successfully uninstalled nvidia-nvshmem-cu13-3.4.5
  Attempting uninstall: nvidia-nvjitlink
    Found existing installation: nvidia-nvjitlink 13.3.33
    Uninstalling nvidia-nvjitlink-13.3.33:
      Successfully uninstalled nvidia-nvjitlink-13.3.33
  Attempting uninstall: nvidia-nccl-cu13
    Found existing installation: nvidia-nccl-cu13 2.29.7
    Uninstalling nvidia-nccl-cu13-2.29.7:
      Successfully uninstalled nvidia-nccl-cu13-2.29.7
  Attempting uninstall: nvidia-curand
    Found existing installation: nvidia-curand 10.4.0.35
    Uninstalling nvidia-curand-10.4.0.35:
      Successfully uninstalled nvidia-curand-10.4.0.35
  Attempting uninstall: nvidia-cufile
    Found existing installation: nvidia-cufile 1.15.1.6
    Uninstalling nvidia-cufile-1.15.1.6:
      Successfully uninstalled nvidia-cufile-1.15.1.6
  Attempting uninstall: nvidia-cuda-runtime
    Found existing installation: nvidia-cuda-runtime 13.0.96
    Uninstalling nvidia-cuda-runtime-13.0.96:
      Successfully uninstalled nvidia-cuda-runtime-13.0.96
  Attempting uninstall: nvidia-cuda-nvrtc
    Found existing installation: nvidia-cuda-nvrtc 13.0.88
    Uninstalling nvidia-cuda-nvrtc-13.0.88:
      Successfully uninstalled nvidia-cuda-nvrtc-13.0.88
  Attempting uninstall: nvidia-cuda-cupti
    Found existing installation: nvidia-cuda-cupti 13.0.85
    Uninstalling nvidia-cuda-cupti-13.0.85:
      Successfully uninstalled nvidia-cuda-cupti-13.0.85
  Attempting uninstall: networkx
    Found existing installation: networkx 3.6.1
    Uninstalling networkx-3.6.1:
      Successfully uninstalled networkx-3.6.1
  Attempting uninstall: MarkupSafe
    Found existing installation: MarkupSafe 3.0.3
    Uninstalling MarkupSafe-3.0.3:
      Successfully uninstalled MarkupSafe-3.0.3
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2026.7.0
    Uninstalling fsspec-2026.7.0:
      Successfully uninstalled fsspec-2026.7.0
  Attempting uninstall: filelock
    Found existing installation: filelock 3.32.3
    Uninstalling filelock-3.32.3:
      Successfully uninstalled filelock-3.32.3
  Attempting uninstall: cuda-pathfinder
    Found existing installation: cuda-pathfinder 1.6.1
    Uninstalling cuda-pathfinder-1.6.1:
      Successfully uninstalled cuda-pathfinder-1.6.1
  Attempting uninstall: nvidia-cusparse
    Found existing installation: nvidia-cusparse 12.6.3.3
    Uninstalling nvidia-cusparse-12.6.3.3:
      Successfully uninstalled nvidia-cusparse-12.6.3.3
  Attempting uninstall: nvidia-cufft
    Found existing installation: nvidia-cufft 12.0.0.61
    Uninstalling nvidia-cufft-12.0.0.61:
      Successfully uninstalled nvidia-cufft-12.0.0.61
  Attempting uninstall: nvidia-cublas
    Found existing installation: nvidia-cublas 13.1.1.3
    Uninstalling nvidia-cublas-13.1.1.3:
      Successfully uninstalled nvidia-cublas-13.1.1.3
  Attempting uninstall: jinja2
    Found existing installation: Jinja2 3.1.6
    Uninstalling Jinja2-3.1.6:
      Successfully uninstalled Jinja2-3.1.6
  Attempting uninstall: cuda-bindings
    Found existing installation: cuda-bindings 13.3.1
    Uninstalling cuda-bindings-13.3.1:
      Successfully uninstalled cuda-bindings-13.3.1
  Attempting uninstall: nvidia-cusolver
    Found existing installation: nvidia-cusolver 12.0.4.66
    Uninstalling nvidia-cusolver-12.0.4.66:
      Successfully uninstalled nvidia-cusolver-12.0.4.66
  Attempting uninstall: nvidia-cudnn-cu13
    Found existing installation: nvidia-cudnn-cu13 9.20.0.48
    Uninstalling nvidia-cudnn-cu13-9.20.0.48:
      Successfully uninstalled nvidia-cudnn-cu13-9.20.0.48
  Attempting uninstall: torch
    Found existing installation: torch 2.13.0
    Uninstalling torch-2.13.0:
      Successfully uninstalled torch-2.13.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ipython 7.34.0 requires jedi>=0.16, which is not installed.
datasets 4.0.0 requires fsspec[http]<=2025.3.0,>=2023.1.0, but you have fsspec 2026.7.0 which is incompatible.
libcuml-cu12 26.2.0 requires cuda-toolkit[cublas,cufft,curand,cusolver,cusparse]==12.*, but you have cuda-toolkit 13.0.3.0 which is incompatible.
libcuvs-cu12 26.2.0 requires cuda-toolkit[cublas,curand,cusolver,cusparse]==12.*, but you have cuda-toolkit 13.0.3.0 which is incompatible.
cudf-cu12 26.2.1 requires cuda-toolkit[nvcc,nvrtc]==12.*, but you have cuda-toolkit 13.0.3.0 which is incompatible.
cuda-python 12.9.7 requires cuda-bindings~=12.9.7, but you have cuda-bindings 13.3.1 which is incompatible.
libraft-cu12 26.2.0 requires cuda-toolkit[cublas,curand,cusolver,cusparse]==12.*, but you have cuda-toolkit 13.0.3.0 which is incompatible.
gcsfs 2025.3.0 requires fsspec==2025.3.0, but you have fsspec 2026.7.0 which is incompatible.
cuml-cu12 26.2.0 requires cuda-toolkit[cublas,cufft,curand,cusolver,cusparse]==12.*, but you have cuda-toolkit 13.0.3.0 which is incompatible.
Successfully installed MarkupSafe-3.0.3 cuda-bindings-13.3.1 cuda-pathfinder-1.6.1 cuda-toolkit-13.0.3.0 filelock-3.32.3 fsspec-2026.7.0 jinja2-3.1.6 mpmath-1.3.0 networkx-3.6.1 nvidia-cublas-13.1.1.3 nvidia-cuda-cupti-13.0.85 nvidia-cuda-nvrtc-13.0.88 nvidia-cuda-runtime-13.0.96 nvidia-cudnn-cu13-9.20.0.48 nvidia-cufft-12.0.0.61 nvidia-cufile-1.15.1.6 nvidia-curand-10.4.0.35 nvidia-cusolver-12.0.4.66 nvidia-cusparse-12.6.3.3 nvidia-cusparselt-cu13-0.8.1 nvidia-nccl-cu13-2.29.7 nvidia-nvjitlink-13.3.33 nvidia-nvshmem-cu13-3.4.5 nvidia-nvtx-13.0.85 setuptools-84.0.0 sympy-1.14.0 torch-2.13.0 torchaudio-2.11.0 triton-3.7.1 typing-extensions-4.16.0

In [10]:
from transformers import pipeline

# Model 1

In [11]:
Model_1 = pipeline("text-classification",
    Model="cardiffnlp/twitter-roberta-base-sentiment-latest"
)

[transformers] No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f.
Using a pipeline without specifying a model name and revision in production is not recommended.

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

model.safetensors: reconstructing file:   0%|          |  0.00B /  268MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

In [12]:
Model_1(["الشاورما كانت لذيذا وايد والخدمة سريعة", "المكان مزدحم جدا والأسعار مرتفعة"])

[{'label': 'NEGATIVE', 'score': 0.8095916509628296},
 {'label': 'NEGATIVE', 'score': 0.646678626537323}]

In [13]:
def add_metadata(prediction):
    return {"label": prediction["label"],
        "score": prediction["score"],
        "metadata": "huggingface_AI_model"}

In [14]:
example_prediction = Model_1("The service was exceptionally fast and friendly.")[0]
add_metadata(example_prediction)

{'label': 'POSITIVE',
 'score': 0.9996246099472046,
 'metadata': 'huggingface_AI_model'}

In [15]:
Model1_results = Model_1(T1_df["review_text"].tolist())
Model1_results[:5]

[{'label': 'NEGATIVE', 'score': 0.8901299834251404},
 {'label': 'NEGATIVE', 'score': 0.7892724871635437},
 {'label': 'NEGATIVE', 'score': 0.998389482498169},
 {'label': 'NEGATIVE', 'score': 0.995849609375},
 {'label': 'POSITIVE', 'score': 0.9979596138000488}]

In [16]:
Model1_results_metadata = [add_metadata(result) for result in Model1_results]
Model1_results_metadata[:5]

[{'label': 'NEGATIVE',
  'score': 0.8901299834251404,
  'metadata': 'huggingface_AI_model'},
 {'label': 'NEGATIVE',
  'score': 0.7892724871635437,
  'metadata': 'huggingface_AI_model'},
 {'label': 'NEGATIVE',
  'score': 0.998389482498169,
  'metadata': 'huggingface_AI_model'},
 {'label': 'NEGATIVE',
  'score': 0.995849609375,
  'metadata': 'huggingface_AI_model'},
 {'label': 'POSITIVE',
  'score': 0.9979596138000488,
  'metadata': 'huggingface_AI_model'}]

In [17]:
T1_df["Model1_prediction"] = [
    result["label"].lower() for result in Model1_results]

T1_df["model_1_score"] = [
    result["score"] for result in Model1_results]

T1_df.head()

,id,review_text,true_label,restaurant_name,language,Model1_prediction,model_1_score
0,1,الشاورما الدجاج واللحم كلها حلوة ولذيذة. والكم...,positive,مطعم الشعلة,Arabic,negative,0.890130
1,2,الشعلة نار على علم .. سمعته تسبق اسمه😄 احد افض...,positive,مطعم الشعلة,Arabic,negative,0.789272
2,3,Today I visited for the first time. Half Grill...,negative,مطعم الشعلة,English,negative,0.998389
3,4,Al shola famous for the Turkish grill have the...,neutral,مطعم الشعلة,English,negative,0.995850
4,5,Cut the story short: to know the real taste! I...,positive,HAZE Restaurant,English,positive,0.997960

# Model 2

In [18]:
Model_2 = pipeline(
    "text-classification",
    Model="cardiffnlp/twitter-xlm-roberta-base-sentiment")

[transformers] No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f.
Using a pipeline without specifying a model name and revision in production is not recommended.

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

In [19]:
Model2_results = Model_2(T1_df["review_text"].tolist())
Model2_results[:5]

[{'label': 'NEGATIVE', 'score': 0.8901299834251404},
 {'label': 'NEGATIVE', 'score': 0.7892724871635437},
 {'label': 'NEGATIVE', 'score': 0.998389482498169},
 {'label': 'NEGATIVE', 'score': 0.995849609375},
 {'label': 'POSITIVE', 'score': 0.9979596138000488}]

In [20]:
Model2_results_metadata = [add_metadata(result) for result in Model2_results]
Model2_results_metadata[:5]

[{'label': 'NEGATIVE',
  'score': 0.8901299834251404,
  'metadata': 'huggingface_AI_model'},
 {'label': 'NEGATIVE',
  'score': 0.7892724871635437,
  'metadata': 'huggingface_AI_model'},
 {'label': 'NEGATIVE',
  'score': 0.998389482498169,
  'metadata': 'huggingface_AI_model'},
 {'label': 'NEGATIVE',
  'score': 0.995849609375,
  'metadata': 'huggingface_AI_model'},
 {'label': 'POSITIVE',
  'score': 0.9979596138000488,
  'metadata': 'huggingface_AI_model'}]

In [21]:
T1_df["Model2_prediction"] = [result["label"].lower() for result in Model2_results]

T1_df["Model2_score"] = [result["score"] for result in Model2_results]

T1_df.head()

,id,review_text,true_label,restaurant_name,language,Model1_prediction,model_1_score,Model2_prediction,Model2_score
0,1,الشاورما الدجاج واللحم كلها حلوة ولذيذة. والكم...,positive,مطعم الشعلة,Arabic,negative,0.890130,negative,0.890130
1,2,الشعلة نار على علم .. سمعته تسبق اسمه😄 احد افض...,positive,مطعم الشعلة,Arabic,negative,0.789272,negative,0.789272
2,3,Today I visited for the first time. Half Grill...,negative,مطعم الشعلة,English,negative,0.998389,negative,0.998389
3,4,Al shola famous for the Turkish grill have the...,neutral,مطعم الشعلة,English,negative,0.995850,negative,0.995850
4,5,Cut the story short: to know the real taste! I...,positive,HAZE Restaurant,English,positive,0.997960,positive,0.997960

#  Model 3

In [22]:
Model_3 = pipeline(
    "text-classification",
    Model="lxyuan/distilbert-base-multilingual-cased-sentiments-student")

[transformers] No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f.
Using a pipeline without specifying a model name and revision in production is not recommended.

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

In [23]:
Model3_results = Model_3(T1_df["review_text"].tolist())
Model3_results[:5]

[{'label': 'NEGATIVE', 'score': 0.8901299834251404},
 {'label': 'NEGATIVE', 'score': 0.7892724871635437},
 {'label': 'NEGATIVE', 'score': 0.998389482498169},
 {'label': 'NEGATIVE', 'score': 0.995849609375},
 {'label': 'POSITIVE', 'score': 0.9979596138000488}]

In [24]:
Model3_results_metadata = [add_metadata(result) for result in Model3_results]
Model3_results_metadata[:5]

[{'label': 'NEGATIVE',
  'score': 0.8901299834251404,
  'metadata': 'huggingface_AI_model'},
 {'label': 'NEGATIVE',
  'score': 0.7892724871635437,
  'metadata': 'huggingface_AI_model'},
 {'label': 'NEGATIVE',
  'score': 0.998389482498169,
  'metadata': 'huggingface_AI_model'},
 {'label': 'NEGATIVE',
  'score': 0.995849609375,
  'metadata': 'huggingface_AI_model'},
 {'label': 'POSITIVE',
  'score': 0.9979596138000488,
  'metadata': 'huggingface_AI_model'}]

In [25]:
T1_df["Model3_prediction"] = [
    result["label"].lower() for result in Model3_results]

T1_df["Model3_score"] = [
    result["score"] for result in Model3_results]

T1_df.head()

,id,review_text,true_label,restaurant_name,language,Model1_prediction,model_1_score,Model2_prediction,Model2_score,Model3_prediction,Model3_score
0,1,الشاورما الدجاج واللحم كلها حلوة ولذيذة. والكم...,positive,مطعم الشعلة,Arabic,negative,0.890130,negative,0.890130,negative,0.890130
1,2,الشعلة نار على علم .. سمعته تسبق اسمه😄 احد افض...,positive,مطعم الشعلة,Arabic,negative,0.789272,negative,0.789272,negative,0.789272
2,3,Today I visited for the first time. Half Grill...,negative,مطعم الشعلة,English,negative,0.998389,negative,0.998389,negative,0.998389
3,4,Al shola famous for the Turkish grill have the...,neutral,مطعم الشعلة,English,negative,0.995850,negative,0.995850,negative,0.995850
4,5,Cut the story short: to know the real taste! I...,positive,HAZE Restaurant,English,positive,0.997960,positive,0.997960,positive,0.997960

# Evaluation

In [26]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

In [27]:
def Evaluate_Model(true_labels, predicted_labels):
    print("Accuracy: ", accuracy_score(true_labels, predicted_labels))
    print("Precision: ", precision_score(true_labels, predicted_labels, average="weighted", zero_division=0))
    print("Recall: ", recall_score(true_labels, predicted_labels, average="weighted", zero_division=0))
    print("F1 Score: ", f1_score(true_labels, predicted_labels, average="weighted", zero_division=0))
    print()
    print(classification_report(true_labels, predicted_labels, zero_division=0))

Model 1

In [28]:
Evaluate_Model(
    T1_df["true_label"],
    T1_df["Model1_prediction"])

Accuracy:  0.49019607843137253
Precision:  0.42558104322810203
Recall:  0.49019607843137253
F1 Score:  0.4088150303466619

              precision    recall  f1-score   support

    negative       0.43      1.00      0.60        16
     neutral       0.00      0.00      0.00        12
    positive       0.64      0.39      0.49        23

    accuracy                           0.49        51
   macro avg       0.36      0.46      0.36        51
weighted avg       0.43      0.49      0.41        51

In [29]:
confusion_matrix(
    T1_df["true_label"],
    T1_df["Model1_prediction"],
    labels=["negative", "neutral", "positive"])

array([[16,  0,  0],
       [ 7,  0,  5],
       [14,  0,  9]])

Model 2

In [30]:
Evaluate_Model(
    T1_df["true_label"],
    T1_df["Model2_prediction"])

Accuracy:  0.49019607843137253
Precision:  0.42558104322810203
Recall:  0.49019607843137253
F1 Score:  0.4088150303466619

              precision    recall  f1-score   support

    negative       0.43      1.00      0.60        16
     neutral       0.00      0.00      0.00        12
    positive       0.64      0.39      0.49        23

    accuracy                           0.49        51
   macro avg       0.36      0.46      0.36        51
weighted avg       0.43      0.49      0.41        51

In [31]:
confusion_matrix(
    T1_df["true_label"],
    T1_df["Model2_prediction"],
    labels=["negative", "neutral", "positive"])

array([[16,  0,  0],
       [ 7,  0,  5],
       [14,  0,  9]])

Model 3

In [32]:
Evaluate_Model(
    T1_df["true_label"],
    T1_df["Model3_prediction"])

Accuracy:  0.49019607843137253
Precision:  0.42558104322810203
Recall:  0.49019607843137253
F1 Score:  0.4088150303466619

              precision    recall  f1-score   support

    negative       0.43      1.00      0.60        16
     neutral       0.00      0.00      0.00        12
    positive       0.64      0.39      0.49        23

    accuracy                           0.49        51
   macro avg       0.36      0.46      0.36        51
weighted avg       0.43      0.49      0.41        51

In [33]:
confusion_matrix(
    T1_df["true_label"],
    T1_df["Model3_prediction"],
    labels=["negative", "neutral", "positive"])

array([[16,  0,  0],
       [ 7,  0,  5],
       [14,  0,  9]])

# Model Battle

In [34]:
Model_Comparison = pd.DataFrame({
    "Model": [
        "twitter-roberta-base-sentiment-latest",
        "twitter-xlm-roberta-base-sentiment",
        "distilbert-multilingual-sentiments"
    ],
    "Accuracy": [
        accuracy_score(T1_df["true_label"], T1_df["Model1_prediction"]),
        accuracy_score(T1_df["true_label"], T1_df["Model2_prediction"]),
        accuracy_score(T1_df["true_label"], T1_df["Model3_prediction"])
    ],
    "F1": [
        f1_score(T1_df["true_label"], T1_df["Model1_prediction"], average="weighted", zero_division=0),
        f1_score(T1_df["true_label"], T1_df["Model2_prediction"], average="weighted", zero_division=0),
        f1_score(T1_df["true_label"], T1_df["Model3_prediction"], average="weighted", zero_division=0)
    ]
})

Model_Comparison.sort_values("F1", ascending=False)

                                   Model  Accuracy        F1
0  twitter-roberta-base-sentiment-latest  0.490196  0.408815
1     twitter-xlm-roberta-base-sentiment  0.490196  0.408815
2     distilbert-multilingual-sentiments  0.490196  0.408815

# Error Analysis

In [35]:
T1_df["Model1_correct"] = (
    T1_df["true_label"] == T1_df["Model1_prediction"])

Model1_errors = T1_df[
    T1_df["Model1_correct"] == False][[
    "review_text",
    "true_label",
    "Model1_prediction",
  ]]

Model1_errors.head(10)

,review_text,true_label,Model1_prediction
0,الشاورما الدجاج واللحم كلها حلوة ولذيذة. والكم...,positive,negative
1,الشعلة نار على علم .. سمعته تسبق اسمه😄 احد افض...,positive,negative
3,Al shola famous for the Turkish grill have the...,neutral,negative
5,بصراحه جيته على مدح صديقي وكان فوق ماتوقعت الت...,positive,negative
7,الكباب كان لذيذ والدماء لذيذة ولكن باردة، التك...,positive,negative
8,المطعم عريق. جربت عندهم غوزي دجاج وبامية. وتحس...,positive,negative
14,جميل ولكن كان الاكل بارد عباره عن بوفيه مفتوح ...,neutral,negative
15,So we went to Marmaris for the buffet. Honestl...,neutral,positive
16,Huge variety of buffet.....can improve food a ...,neutral,positive
17,ماشاءالله مطعم مميز اجواء جميله العيب الوحيد م...,neutral,positive

In [36]:
T1_df["Model2_correct"] = (
    T1_df["true_label"] == T1_df["Model2_prediction"])

Model2_errors = T1_df[
    T1_df["Model2_correct"] == False][[
    "review_text",
    "true_label",
    "Model1_prediction",
  ]]

Model2_errors.head(10)

,review_text,true_label,Model1_prediction
0,الشاورما الدجاج واللحم كلها حلوة ولذيذة. والكم...,positive,negative
1,الشعلة نار على علم .. سمعته تسبق اسمه😄 احد افض...,positive,negative
3,Al shola famous for the Turkish grill have the...,neutral,negative
5,بصراحه جيته على مدح صديقي وكان فوق ماتوقعت الت...,positive,negative
7,الكباب كان لذيذ والدماء لذيذة ولكن باردة، التك...,positive,negative
8,المطعم عريق. جربت عندهم غوزي دجاج وبامية. وتحس...,positive,negative
14,جميل ولكن كان الاكل بارد عباره عن بوفيه مفتوح ...,neutral,negative
15,So we went to Marmaris for the buffet. Honestl...,neutral,positive
16,Huge variety of buffet.....can improve food a ...,neutral,positive
17,ماشاءالله مطعم مميز اجواء جميله العيب الوحيد م...,neutral,positive

In [37]:
T1_df["Model3_correct"] = (
    T1_df["true_label"] == T1_df["Model3_prediction"])

Model3_errors = T1_df[
    T1_df["Model3_correct"] == False][[
    "review_text",
    "true_label",
    "Model3_prediction",
  ]]

Model3_errors.head(10)

,review_text,true_label,Model3_prediction
0,الشاورما الدجاج واللحم كلها حلوة ولذيذة. والكم...,positive,negative
1,الشعلة نار على علم .. سمعته تسبق اسمه😄 احد افض...,positive,negative
3,Al shola famous for the Turkish grill have the...,neutral,negative
5,بصراحه جيته على مدح صديقي وكان فوق ماتوقعت الت...,positive,negative
7,الكباب كان لذيذ والدماء لذيذة ولكن باردة، التك...,positive,negative
8,المطعم عريق. جربت عندهم غوزي دجاج وبامية. وتحس...,positive,negative
14,جميل ولكن كان الاكل بارد عباره عن بوفيه مفتوح ...,neutral,negative
15,So we went to Marmaris for the buffet. Honestl...,neutral,positive
16,Huge variety of buffet.....can improve food a ...,neutral,positive
17,ماشاءالله مطعم مميز اجواء جميله العيب الوحيد م...,neutral,positive

# Task B — Zero-Shot Classification

*   List item
*   List item

In [38]:
classifier = pipeline(
    "zero-shot-classification",
    model="MoritzLaurer/mDeBERTa-v3-base-mnli-xnli"
)

config.json:   0%|          | 0.00/1.07k [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  558MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/202 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/1.26k [00:00<?, ?B/s]

spm.model: reconstructing file:   0%|          |  0.00B / 4.31MB

spm.model: downloading bytes:           |  0.00B

tokenizer.json: reconstructing file:   0%|          |  0.00B / 16.3MB

tokenizer.json: downloading bytes:           |  0.00B

added_tokens.json:   0%|          | 0.00/23.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/286 [00:00<?, ?B/s]

In [39]:
Sequence_classify = "The prices are a bit high for the portion sizes we received."
candidate_labels = ["Food Quality","Service","Price","Cleanliness","Atmosphere","Location","Waiting Time"]

classifier(
    Sequence_classify,
    candidate_labels,
    multi_label=False
)

{'sequence': 'The prices are a bit high for the portion sizes we received.',
 'labels': ['Price',
  'Service',
  'Food Quality',
  'Location',
  'Atmosphere',
  'Cleanliness',
  'Waiting Time'],
 'scores': [0.6490769982337952,
  0.10492919385433197,
  0.09161028265953064,
  0.05148918554186821,
  0.03803996741771698,
  0.03470349684357643,
  0.030150920152664185]}

In [40]:
Zero_example = classifier(
    Sequence_classify,
    candidate_labels,
    multi_label=False)

Zero_output = {
    "label": Zero_example["labels"][0],
    "score": Zero_example["scores"][0],
    "metadata": "huggingface_AI_model"}

Zero_output

{'label': 'Price',
 'score': 0.6490769982337952,
 'metadata': 'huggingface_AI_model'}

In [41]:
Zero_predictions = []
Zero_scores = []

for review in T2_df["review_text"]:
    result = classifier(
        review,
        candidate_labels,
        multi_label=False
      )

    Zero_predictions.append(result["labels"][0])
    Zero_scores.append(result["scores"][0])

[transformers] You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset

In [42]:
T2_df["predicted_topic"] = Zero_predictions
T2_df["score"] = Zero_scores

T2_df.head()

,id,review_text,restaurant_name,topic_label,predicted_topic,score
0,1,الشاورما الدجاج واللحم كلها حلوة ولذيذة. والكم...,مطعم الشعلة,Location,Service,0.591957
1,2,الشعلة نار على علم .. سمعته تسبق اسمه😄 احد افض...,مطعم الشعلة,Food Quality,Food Quality,0.616707
2,3,Today I visited for the first time. Half Grill...,مطعم الشعلة,Food Quality,Service,0.431493
3,4,Al shola famous for the Turkish grill have the...,مطعم الشعلة,Location,Food Quality,0.412155
4,5,Cut the story short: to know the real taste! B...,HAZE Restaurant,Price,Food Quality,0.584621

In [47]:
print("Accuracy:", accuracy_score(
    T2_df["topic_label"],
    T2_df["predicted_topic"]))

print("F1 Score:", f1_score(
    T2_df["topic_label"],
    T2_df["predicted_topic"],
    average="weighted",
    zero_division=0))

Accuracy: 0.14285714285714285
F1 Score: 0.14285714285714285

In [49]:
print(classification_report(
    T2_df["topic_label"],
    T2_df["predicted_topic"],
    zero_division=0))

              precision    recall  f1-score   support

  Atmosphere       0.50      0.14      0.22         7
 Cleanliness       0.00      0.00      0.00         3
Food Quality       0.25      0.25      0.25         8
    Location       0.00      0.00      0.00         8
       Price       0.25      0.50      0.33         2
     Service       0.09      0.14      0.11         7
Waiting Time       0.00      0.00      0.00         0

    accuracy                           0.14        35
   macro avg       0.16      0.15      0.13        35
weighted avg       0.19      0.14      0.14        35

In [53]:
T2_df["correct"] = (
    T2_df["topic_label"] == T2_df["predicted_topic"])

zero_errors = T2_df[
    T2_df["correct"] == False]

[[
    "review",
    "true_topic",
    "predicted_topic",
    "score"]]
zero_errors.head(10)

,id,review_text,restaurant_name,topic_label,predicted_topic,score,correct
0,1,الشاورما الدجاج واللحم كلها حلوة ولذيذة. والكم...,مطعم الشعلة,Location,Service,0.591957,False
2,3,Today I visited for the first time. Half Grill...,مطعم الشعلة,Food Quality,Service,0.431493,False
3,4,Al shola famous for the Turkish grill have the...,مطعم الشعلة,Location,Food Quality,0.412155,False
4,5,Cut the story short: to know the real taste! B...,HAZE Restaurant,Price,Food Quality,0.584621,False
5,6,بصراحه جيته على مدح صديقي وكان فوق ماتوقعت الت...,HAZE Restaurant,Service,Cleanliness,0.585900,False
6,7,Excellent food and service,HAZE Restaurant,Service,Food Quality,0.563330,False
8,9,المطعم عريق. جربت عندهم غوزي دجاج وبامية. وتحس...,مطعم العراقين,Location,Food Quality,0.727547,False
9,10,للأسف كانت تجربة غير موفقة. الأثاث ما زال قديم...,مطعم العراقين,Food Quality,Location,0.512630,False
10,11,أكل لذيذ جداً وأنصح به الجميع ولكن الأسعار مرت...,مطعم مرمريز,Location,Price,0.631020,False
11,12,الخدمة بطيئة جداً وتأخر الطلب أكثر من ساعة رغم...,مطعم مرمريز,Location,Service,0.839503,False

## Domain Shift
The models were trained on Twitter data, not restaurant reviews. Vocabulary and structures differ, leading to errors in neutral or restaurant-specific texts.

## Final Recommendation
Choose cardiffnlp/twitter-roberta-base-sentiment-latest for the best balance of accuracy and F1 score on our dataset.

# Reflection Questions

- What surprised you?
   - Pretrained social media models classified many restaurant reviews correctly without custom training.

- What caused failures?
  - Ambiguous, neutral, and mixed-sentiment reviews lacking strong polarity.

- Are larger models better?
  - No, performance depends on task alignment and domain fit.
  
- How important is training data?
    - Very important; original domain patterns may not match local restaurant reviews.
    
- What did you learn from the model card?
  - Task architecture, training data, licenses, and limitations.  Pretrained vs.
   
- From Scratch?
  - Pretrained models leverage learned patterns; training from scratch starts randomly and needs massive data.
  
- When is fine-tuning worth it?
  - When the pretrained model repeatedly fails on specific domain language.

- With 10x more data?
  - Build a larger evaluation set and fine-tune the best pretrained model.  
  
- Deploy in a real app?
  - Only after extensive testing on real feedback and handling edge cases.

# Future Work

- ProposalCollect more real restaurant reviews containing sarcasm and local expressions.

- Fine-tune the best sentiment model on this local dataset.

- Compare accuracy, F1 score, and performance against the original model

# Save Results

In [54]:
T1_df.to_csv("T1_results.csv", index=False)
T2_df.to_csv("T2_results.csv", index=False)
Model_Comparison.to_csv("model_comparison.csv", index=False)